---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "deploy_nsswitch.yml"
  when:
    - "hostvars[inventory_hostname]['nsswitch'] is defined"
    - "hostvars[inventory_hostname]['nsswitch'] != ''"
