---
- name: "nsswitch | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "nsswitch | Include deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.yml"
  when:
    - "hostvars[inventory_hostname]['nsswitch'] is defined"
    - "hostvars[inventory_hostname]['nsswitch'] != []"
    - "hostvars[inventory_hostname]['nsswitch'] != ''"
    - "hostvars[inventory_hostname]['nsswitch'] != None"
