---
# /etc not exists, something wrong with this system
- name: "nsswitch | Check /etc exists"
  ansible.builtin.stat:
    path: "/etc"
  register: "nsswitch_etc_stat"
  failed_when: "nsswitch_etc_stat.stat.exists == False"
